Testing new ScrollView
Currently it's buggy, throwing the following error:
The following NoSuchMethodError was thrown while resolving an image:
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()